package com.example.telegramuserbot.domain;

import org.springframework.data.annotation.Id;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.LocalDateTime;

/**
 * Represents a detected market event from message analysis.
 * Events are generated by fn_detect_events() function and tracked through their lifecycle.
 */
@Table(schema = "tgscan", name = "events")
public final class Event {

    @Id
    private Long id;

    @Column("event_type")
    private String eventType;

    @Column("topic")
    private String topic;

    @Column("window_start")
    private LocalDateTime windowStart;

    @Column("window_end")
    private LocalDateTime windowEnd;

    @Column("message_count")
    private Integer messageCount;

    @Column("unique_sources")
    private Integer uniqueSources;

    @Column("avg_importance")
    private Double avgImportance;

    @Column("panic_ratio")
    private Double panicRatio;

    @Column("spike_ratio")
    private Double spikeRatio;

    @Column("top_sources")
    private String topSources; // JSONB stored as String

    @Column("root_cause")
    private String rootCause;

    @Column("confidence")
    private Double confidence;

    @Column("severity")
    private String severity;

    @Column("evidence")
    private String evidence; // JSONB stored as String

    @Column("created_at")
    private LocalDateTime createdAt;

    @Column("updated_at")
    private LocalDateTime updatedAt;

    @Column("last_alert_at")
    private LocalDateTime lastAlertAt;

    @Column("rate_limit_key")
    private String rateLimitKey;

    @Column("status")
    private String status;

    @Column("processed_at")
    private LocalDateTime processedAt;

    @Column("processing_error")
    private String processingError;

    /**
     * Default constructor for R2DBC mapping.
     */
    public Event() {
    }

    // Getters and Setters

    public Long id() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String eventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String topic() {
        return topic;
    }

    public void setTopic(String topic) {
        this.topic = topic;
    }

    public LocalDateTime windowStart() {
        return windowStart;
    }

    public void setWindowStart(LocalDateTime windowStart) {
        this.windowStart = windowStart;
    }

    public LocalDateTime windowEnd() {
        return windowEnd;
    }

    public void setWindowEnd(LocalDateTime windowEnd) {
        this.windowEnd = windowEnd;
    }

    public Integer messageCount() {
        return messageCount;
    }

    public void setMessageCount(Integer messageCount) {
        this.messageCount = messageCount;
    }

    public Integer uniqueSources() {
        return uniqueSources;
    }

    public void setUniqueSources(Integer uniqueSources) {
        this.uniqueSources = uniqueSources;
    }

    public Double avgImportance() {
        return avgImportance;
    }

    public void setAvgImportance(Double avgImportance) {
        this.avgImportance = avgImportance;
    }

    public Double panicRatio() {
        return panicRatio;
    }

    public void setPanicRatio(Double panicRatio) {
        this.panicRatio = panicRatio;
    }

    public Double spikeRatio() {
        return spikeRatio;
    }

    public void setSpikeRatio(Double spikeRatio) {
        this.spikeRatio = spikeRatio;
    }

    public String topSources() {
        return topSources;
    }

    public void setTopSources(String topSources) {
        this.topSources = topSources;
    }

    public String rootCause() {
        return rootCause;
    }

    public void setRootCause(String rootCause) {
        this.rootCause = rootCause;
    }

    public Double confidence() {
        return confidence;
    }

    public void setConfidence(Double confidence) {
        this.confidence = confidence;
    }

    public String severity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public String evidence() {
        return evidence;
    }

    public void setEvidence(String evidence) {
        this.evidence = evidence;
    }

    public LocalDateTime createdAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime updatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime lastAlertAt() {
        return lastAlertAt;
    }

    public void setLastAlertAt(LocalDateTime lastAlertAt) {
        this.lastAlertAt = lastAlertAt;
    }

    public String rateLimitKey() {
        return rateLimitKey;
    }

    public void setRateLimitKey(String rateLimitKey) {
        this.rateLimitKey = rateLimitKey;
    }

    public String status() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime processedAt() {
        return processedAt;
    }

    public void setProcessedAt(LocalDateTime processedAt) {
        this.processedAt = processedAt;
    }

    public String processingError() {
        return processingError;
    }

    public void setProcessingError(String processingError) {
        this.processingError = processingError;
    }

    @Override
    public String toString() {
        return String.format(
            "[%s] %s | severity=%s conf=%.2f msgs=%d sources=%d | %s",
            eventType,
            topic,
            severity,
            confidence != null ? confidence : 0.0,
            messageCount != null ? messageCount : 0,
            uniqueSources != null ? uniqueSources : 0,
            rootCause
        );
    }
}
