package com.example.telegramuserbot.domain;

/**
 * Enum to categorize different types of messages for proper handling and filtering
 */
public enum MessageType {
    /**
     * Regular user message (text, media, etc.)
     */
    USER_MESSAGE("User Message"),
    
    /**
     * AI assistant response message
     */
    AI_RESPONSE("AI Response"),
    
    /**
     * System/service message generated by commands or system operations
     * These should be filtered from LLM conversation history
     */
    SERVICE_MESSAGE("Service Message"),
    
    /**
     * Command response message (like /enable_config, /list_channels responses)
     */
    COMMAND_RESPONSE("Command Response"),
    
    /**
     * Profile information message (user profile display)
     */
    PROFILE_MESSAGE("Profile Message"),
    
    /**
     * Sync operation status/result message
     */
    SYNC_MESSAGE("Sync Message"),
    
    /**
     * System notification message
     */
    SYSTEM_NOTIFICATION("System Notification"),

    /**
     * Synthetic news article harvested from a web RSS/Atom feed by the web collector.
     * Stored under a negative synthetic chat_id matching a bot.web_sources row.
     * Never outgoing; treated as a first-class news source by the ranking brain.
     */
    WEB_NEWS("Web News"),

    /**
     * Synthetic news story harvested from Hacker News via the Firebase API.
     * Stored under the HN synthetic chat_id ({@code -8000000001L}).
     * {@code views} = HN score (upvotes), {@code forwards} = comment count — real engagement
     * signals that let the ranking brain treat HN stories as first-class news peers.
     * Never outgoing.
     */
    HN_NEWS("HN News");

    private final String description;
    
    MessageType(String description) {
        this.description = description;
    }
    
    public String getDescription() {
        return description;
    }
    
    /**
     * Check if this message type should be included in LLM conversation history
     */
    public boolean isIncludedInLlmConversation() {
        return switch (this) {
            case USER_MESSAGE, AI_RESPONSE -> true;
            case SERVICE_MESSAGE, COMMAND_RESPONSE, PROFILE_MESSAGE,
                 SYNC_MESSAGE, SYSTEM_NOTIFICATION, WEB_NEWS, HN_NEWS -> false;
        };
    }

    /**
     * Check if this message type is a service-related message
     */
    public boolean isServiceType() {
        return switch (this) {
            case USER_MESSAGE, AI_RESPONSE, WEB_NEWS, HN_NEWS -> false;
            case SERVICE_MESSAGE, COMMAND_RESPONSE, PROFILE_MESSAGE,
                 SYNC_MESSAGE, SYSTEM_NOTIFICATION -> true;
        };
    }
}