#!/usr/bin/env bash
# Send/receive check against the chats reserved for testing.
#
#   scripts/test-chat-roundtrip.sh [chatId]
#
# Run it after changing anything on the reply path. It uses the running app's
# /api/admin/test-chat endpoints, which refuse any chat that is not listed in
# bot.app_settings 'test.chats', so it can never touch a live conversation.
#
# What it proves, in order:
#   1. outbound — a persona puts a line into the test chat and Telegram accepts it
#   2. inbound  — that line comes back from Telegram and is persisted
#   3. reply    — an incoming human message replayed through Kafka produces a real
#                 persona reply, generated by the LLM and delivered to Telegram
#
# Exit code 0 only if all three hold.
set -uo pipefail

APP="${APP_URL:-http://localhost:8099}"
PSQL=(docker exec tg-orch-postgres psql -U staging -d news_aggregator_db -At)
STAMP="$(date +%H%M%S)"
PROBE="roundtrip probe ${STAMP}"
FAILED=0

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[32mOK\033[0m   %s\n' "$*"; }
bad()  { printf '  \033[31mFAIL\033[0m %s\n' "$*"; FAILED=1; }
json() { python3 -c 'import json,sys;d=json.load(sys.stdin);print(d.get(sys.argv[1],""))' "$1"; }

say "test chats"
CHATS_JSON="$(curl -s -m 10 "$APP/api/admin/test-chat")" || { bad "app not reachable at $APP"; exit 1; }
CHAT="${1:-$(printf '%s' "$CHATS_JSON" | python3 -c 'import json,sys;ids=json.load(sys.stdin)["chatIds"];print(ids[0] if ids else "")')}"
[ -n "$CHAT" ] || { bad "no test chats configured (bot.app_settings test.chats)"; exit 1; }
printf '  app=%s chat=%s\n' "$APP" "$CHAT"

# The persona that is bound to this chat and allowed to reply.
BOT="$("${PSQL[@]}" -c "select bot_id from bot.persona_chat_bindings
                         where chat_id=$CHAT and reply_enabled
                         order by reply_probability desc limit 1;")"
[ -n "$BOT" ] || { bad "no enabled persona binding for chat $CHAT"; exit 1; }
printf '  persona=%s\n' "$BOT"

KILL="$(curl -s -m 10 "$APP/api/admin/kill-switch" | json active)"
[ "$KILL" = "False" ] || [ "$KILL" = "false" ] || printf '  \033[33mnote\033[0m kill switch is active — sends will be suppressed\n'

say "1. outbound: persona -> Telegram"
SEND="$(curl -s -m 120 -X POST "$APP/api/admin/test-chat/send" -H 'Content-Type: application/json' \
        -d "{\"botId\":\"$BOT\",\"chatId\":$CHAT,\"text\":\"$PROBE\"}")"
TG_ID="$(printf '%s' "$SEND" | json telegramMessageId)"
if [ -n "$TG_ID" ] && [ "$TG_ID" != "None" ]; then
  ok "Telegram accepted the message (id=$TG_ID)"
else
  bad "send refused: $SEND"
fi

say "2. inbound: Telegram -> database"
FOUND=""
for _ in $(seq 1 20); do
  FOUND="$("${PSQL[@]}" -c "select message_id from bot.messages
                             where chat_id=$CHAT and content = '$PROBE' limit 1;")"
  [ -n "$FOUND" ] && break
  sleep 3
done
if [ -n "$FOUND" ]; then ok "persisted as message_id=$FOUND"; else bad "the probe never reached bot.messages"; fi

say "3. reply: incoming message -> persona answer"
TRIGGER="$("${PSQL[@]}" -c "select message_id from bot.messages
                             where chat_id=$CHAT and not is_outgoing
                               and content is not null and length(content) > 15
                             order by date desc limit 1;")"
if [ -z "$TRIGGER" ]; then
  bad "no incoming human message in this chat to reply to — write one and re-run"
else
  BEFORE="$("${PSQL[@]}" -c "select count(*) from bot.messages where chat_id=$CHAT and is_outgoing;")"
  RESP="$(curl -s -m 30 -X POST "$APP/api/admin/test-chat/trigger" -H 'Content-Type: application/json' \
          -d "{\"chatId\":$CHAT,\"messageId\":$TRIGGER}")"
  printf '  replaying message_id=%s\n' "$TRIGGER"
  case "$RESP" in
    *'"triggered":true'*) : ;;
    *) bad "trigger refused: $RESP" ;;
  esac
  REPLY=""
  # Generation is seconds; the human send pacing adds up to ~2 minutes on purpose.
  for _ in $(seq 1 40); do
    AFTER="$("${PSQL[@]}" -c "select count(*) from bot.messages where chat_id=$CHAT and is_outgoing;")"
    if [ "$AFTER" -gt "$BEFORE" ]; then
      REPLY="$("${PSQL[@]}" -c "select content from bot.messages
                                 where chat_id=$CHAT and is_outgoing order by date desc limit 1;")"
      break
    fi
    sleep 5
  done
  if [ -n "$REPLY" ]; then
    ok "persona replied: $REPLY"
  else
    SKIP="$("${PSQL[@]}" -c "select coalesce(skip_reason,'-') from bot.llm_queries
                              where chat_id=$CHAT order by triggered_at desc limit 1;")"
    bad "no reply within ~3 min (last decision: $SKIP)"
  fi
fi

say "result"
if [ "$FAILED" = 0 ]; then ok "send, receive and reply all work"; else bad "see above"; fi
exit "$FAILED"
